const CONFIG = {
    titleWeb: "Special ",
    introTitle: 'Bé iu',
    introDesc: `Hellu người tớ iu <3`,
    btnIntro: '',
    title: 'Bé có biết hôm nay là ngày gì không?',
    desc: ' ',
    btnYes: 'Có',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại yêu mình <3',
    btnReply: 'Hihi',
    reply: 'Vì bạn đẹp ',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối nay 7h, mình qua đón đi chơi nha.',
    btnAccept: 'Okiiiii lun <3',
}
